### PR TITLE
PMM-3669 get correct available version for update

### PR DESCRIPTION
**Pull request by hors**
* on pmm v1 all available v2 scenarios are skipped
    * on pmm v2 all available v1 scenarios are skipped

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/pmm-update?pullRequest=24) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm-update?pullRequest=24) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm-update?pullRequest=24) it.</sub>

**Comment by delgod** [comment]
Do we really need two different packages? pmm-update and pmm2-update?

**Comment by hors** [comment]
@AlekSi 
Why do we need to produce and support additional branches? We can use one branch for pmm and pmm2 and commit all ansible playbooks to this branch. In this case we will have a lot of advantages. e.g. it will be easier to maintain  this repo and we will have only one package.

**Comment by rnovikovP** [comment]
The idea of have 2 packages is from me and we need this to have flexibility later on changing pmm2 update process. 
But, we need to keep  1.X branch working. 
Note: there  a lot of people who are on old version 1.x and they have updater  working  as :  "take latest package and  execute it"
But  we can't let them upgrade to version 2 using the button. 


See  pmm1 and pmm2 as two separate products

**Comment by rnovikovP** [comment]
Let's keep verification on version number for 1.X to ensure we not updating 1.X to 2X

**Pull request merged**
