### PR TITLE
PMM-8169: Improve Release date capture for PMM server

### PR DESCRIPTION
**Pull request by denisok**
Replace BuildDate with the repoinfo instead of package info, so package
don't need to be rebuild on the release date. repoinfo date updates on
release date.

### CODE REVIEW

**Comment by denisok** [comment]
test are actually passed excep that wierd D-bus thing, that is probably something to do with ansible as I can't reproduce it by just `yum update`.

**Comment by denisok** [comment]
OK, as I thought - it was ansible issue - I have added update for the ansible and now it passed.

**Review by adivinho — APPROVED** [review]

**Review by BupycHuk — COMMENTED** [review]
Looks good to me, link to FB?

**Comment by denisok** [comment]
https://github.com/Percona-Lab/pmm-submodules/pull/1847

**Review by BupycHuk — APPROVED** [review]

**Pull request merged**
